"""add evaluations and absence reports

Revision ID: afa36a5f430a
Revises: b639f04c2604
Create Date: 2026-05-09 14:02:11.046616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa36a5f430a'
down_revision = 'b639f04c2604'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absence_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('nb_seances', sa.Integer(), nullable=True),
    sa.Column('nb_absences', sa.Integer(), nullable=True),
    sa.Column('nb_retards', sa.Integer(), nullable=True),
    sa.Column('taux_presence', sa.Float(), nullable=True),
    sa.Column('periode_debut', sa.DateTime(), nullable=True),
    sa.Column('periode_fin', sa.DateTime(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('gravite', sa.Enum('INFO', 'ATTENTION', 'CRITIQUE', name='absencegravite'), nullable=True),
    sa.Column('statut', sa.Enum('NOUVEAU', 'VU', 'TRAITE', name='absencereportstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('admin_treated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('note_participation', sa.Float(), nullable=True),
    sa.Column('note_travail', sa.Float(), nullable=True),
    sa.Column('note_comportement', sa.Float(), nullable=True),
    sa.Column('note_assiduite', sa.Float(), nullable=True),
    sa.Column('note_globale', sa.Float(), nullable=True),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('statut', sa.Enum('BROUILLON', 'ENVOYEE', 'ARCHIVEE', name='evaluationstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('admin_commentaire', sa.Text(), nullable=True),
    sa.Column('admin_archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluations')
    op.drop_table('absence_reports')
    # ### end Alembic commands ###
