"""add indexes

Revision ID: b639f04c2604
Revises: 5edc257fe7a6
Create Date: 2026-05-08 00:57:18.081885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b639f04c2604'
down_revision = '5edc257fe7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index('ix_enroll_course_id', ['course_id'], unique=False)
        batch_op.create_index('ix_enroll_student_id', ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index('ix_enroll_student_id')
        batch_op.drop_index('ix_enroll_course_id')

    # ### end Alembic commands ###
